steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/proyecto3-back", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/proyecto3-back"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["run", "deploy", "proyecto3-back", "--image", "gcr.io/$PROJECT_ID/proyecto3-back", "--platform", "managed"]